CREATE TABLE `background_jobs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`bg_job_type` enum('export_ml','generate_titles','generate_descriptions','generate_images') NOT NULL,
	`bg_job_status` enum('scheduled','queued','processing','completed','failed','cancelled') NOT NULL DEFAULT 'queued',
	`marketplaceId` int,
	`accountId` int,
	`accountName` varchar(256),
	`tagFilter` varchar(256),
	`listingTypes` json,
	`titleStyle` varchar(64),
	`descriptionStyle` varchar(64),
	`imageStyle` varchar(64),
	`concurrency` int NOT NULL DEFAULT 5,
	`productIds` json,
	`productData` json,
	`totalItems` int NOT NULL DEFAULT 0,
	`processedItems` int NOT NULL DEFAULT 0,
	`successCount` int NOT NULL DEFAULT 0,
	`errorCount` int NOT NULL DEFAULT 0,
	`scheduledFor` timestamp,
	`startedAt` timestamp,
	`completedAt` timestamp,
	`lastError` text,
	`resultLog` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `background_jobs_id` PRIMARY KEY(`id`)
);
