CREATE TABLE `shopee_accounts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`shopId` bigint NOT NULL,
	`shopName` varchar(256),
	`region` varchar(10) NOT NULL DEFAULT 'BR',
	`accessToken` text NOT NULL,
	`refreshToken` text NOT NULL,
	`tokenExpiresAt` timestamp NOT NULL,
	`shopStatus` varchar(64),
	`totalProducts` int DEFAULT 0,
	`isActive` int NOT NULL DEFAULT 1,
	`lastSyncAt` timestamp,
	`lastUsedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `shopee_accounts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `shopee_products` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`shopeeAccountId` int NOT NULL,
	`itemId` bigint NOT NULL,
	`itemName` varchar(1024),
	`itemSku` varchar(256),
	`itemStatus` varchar(32),
	`categoryId` bigint,
	`categoryName` varchar(512),
	`price` varchar(32),
	`stock` int DEFAULT 0,
	`sold` int DEFAULT 0,
	`rating` varchar(10),
	`imageUrl` varchar(1024),
	`images` json,
	`hasVideo` int DEFAULT 0,
	`attributes` json,
	`attributesFilled` int DEFAULT 0,
	`attributesTotal` int DEFAULT 0,
	`qualityScore` varchar(32),
	`variations` json,
	`weight` varchar(32),
	`dimensionLength` varchar(32),
	`dimensionWidth` varchar(32),
	`dimensionHeight` varchar(32),
	`description` text,
	`lastSyncAt` timestamp NOT NULL DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `shopee_products_id` PRIMARY KEY(`id`)
);
